PRETRAIN_TASK_1='nsp'
PRETRAIN_TASK_2='nss'
PRETRAIN_TASK_3='ss'
DATA_PATH_1='./pretrain_data/preprocessed/nsp-250/nsp_document'
DATA_PATH_2='./pretrain_data/preprocessed/nss-250/nss_document'
DATA_PATH_3='./pretrain_data/preprocessed/ss-250/ss_document'
PREDATASET_MAX_SEQ_LENGTH_1=412
PREDATASET_MAX_SEQ_LENGTH_2=412
PREDATASET_MAX_SEQ_LENGTH_3=412

NSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0=16
NSP_GRADIENT_ACCUMULATION_STEPS=1
NSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1=8
NSP_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1=8

NSP_NUM_TASKS_TRAIN=8
NSP_NUM_TASKS_TEST=4
NSP_NUM_DOMAINS=250
NSP_K_SUPPORT=16
NSP_K_QUERY=16
NSP_MAX_SEQ_LENGTH=412

NSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0=8
NSS_GRADIENT_ACCUMULATION_STEPS=2
NSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1=4
NSS_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1=4

NSS_NUM_TASKS_TRAIN=8
NSS_NUM_TASKS_TEST=4
NSS_NUM_DOMAINS=250
NSS_K_SUPPORT=16
NSS_K_QUERY=16
NSS_MAX_SEQ_LENGTH=412

SCSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0=16
SCSP_GRADIENT_ACCUMULATION_STEPS=1
SCSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1=8
SCSP_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1=8

SCSP_NUM_TASKS_TRAIN=8
SCSP_NUM_TASKS_TEST=4
SCSP_NUM_DOMAINS=250
SCSP_K_SUPPORT=8
SCSP_K_QUERY=8
SCSP_MAX_SEQ_LENGTH=412

SCSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0=8
SCSS_GRADIENT_ACCUMULATION_STEPS=2
SCSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1=4
SCSS_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1=4

SCSS_NUM_TASKS_TRAIN=8
SCSS_NUM_TASKS_TEST=4
SCSS_NUM_DOMAINS=250
SCSS_K_SUPPORT=4
SCSS_K_QUERY=4
SCSS_MAX_SEQ_LENGTH=412

SCC_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0=16
SCC_GRADIENT_ACCUMULATION_STEPS=1
SCC_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1=8
SCC_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1=8

SCC_NUM_TASKS_TRAIN=8
SCC_NUM_TASKS_TEST=4
SCC_NUM_DOMAINS=250
SCC_K_SUPPORT=4
SCC_K_QUERY=4
SCC_MAX_SEQ_LENGTH=412

CLUSTER_DIR_3='./pretrain_data/preprocessed/ss-250/cluster_center.npy'
CLUSTER_DIR_1='./pretrain_data/preprocessed/nsp-250/cluster_center.npy'
CLUSTER_DIR_2='./pretrain_data/preprocessed/nss-250/cluster_center.npy'
CLASSIFY_NUM=4
NEG_SENT=3

TOTAL_STEPS=100000
OUTER_BATCH_SIZE=4
SAVE_STEP=100
TEST_STEP=1000
SAVE_INTERVAL=500
MAX_DEC_LENGTH=3

OPTS=""
OPTS+=" --pretrain_task ${PRETRAIN_TASK_1} ${PRETRAIN_TASK_2} ${PRETRAIN_TASK_3}"
OPTS+=" --data_path ${DATA_PATH_1} ${DATA_PATH_2} ${DATA_PATH_3}"
OPTS+=" --predataset_max_seq_length ${PREDATASET_MAX_SEQ_LENGTH_1} ${PREDATASET_MAX_SEQ_LENGTH_2} ${PREDATASET_MAX_SEQ_LENGTH_3}"

OPTS+=" --num_tasks_train ${NSP_NUM_TASKS_TRAIN} ${NSS_NUM_TASKS_TRAIN} ${SCSP_NUM_TASKS_TRAIN} ${SCSS_NUM_TASKS_TRAIN} ${SCC_NUM_TASKS_TRAIN}"
OPTS+=" --num_tasks_test ${NSP_NUM_TASKS_TEST} ${NSS_NUM_TASKS_TEST} ${SCSP_NUM_TASKS_TEST} ${SCSS_NUM_TASKS_TEST} ${SCC_NUM_TASKS_TEST}"
OPTS+=" --num_domains ${NSP_NUM_DOMAINS} ${NSS_NUM_DOMAINS} ${SCSP_NUM_DOMAINS} ${SCSS_NUM_DOMAINS} ${SCC_NUM_DOMAINS}"
OPTS+=" --k_support ${NSP_K_SUPPORT} ${NSS_K_SUPPORT} ${SCSP_K_SUPPORT} ${SCSS_K_SUPPORT} ${SCC_K_SUPPORT}"
OPTS+=" --k_query ${NSP_K_QUERY} ${NSS_K_QUERY} ${SCSP_K_QUERY} ${SCSS_K_QUERY} ${SCC_K_QUERY}"
OPTS+=" --per_device_inner_train_batch_size_0 ${NSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0} ${NSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0} ${SCSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0} ${SCSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0} ${SCC_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_0}"
OPTS+=" --per_device_inner_train_batch_size_1 ${NSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1} ${NSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1} ${SCSP_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1} ${SCSS_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1} ${SCC_PER_DEVICE_INNER_TRAIN_BATCH_SIZE_1}"
OPTS+=" --per_device_inner_eval_batch_size_1 ${NSP_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1} ${NSS_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1} ${SCSP_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1} ${SCSS_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1} ${SCC_PER_DEVICE_INNER_EVAL_BATCH_SIZE_1}"
OPTS+=" --gradient_accumulation_steps ${NSP_GRADIENT_ACCUMULATION_STEPS} ${NSS_GRADIENT_ACCUMULATION_STEPS} ${SCSP_GRADIENT_ACCUMULATION_STEPS} ${SCSS_GRADIENT_ACCUMULATION_STEPS} ${SCC_GRADIENT_ACCUMULATION_STEPS}"
OPTS+=" --max_seq_length ${NSP_MAX_SEQ_LENGTH} ${NSS_MAX_SEQ_LENGTH} ${SCSP_MAX_SEQ_LENGTH} ${SCSS_MAX_SEQ_LENGTH} ${SCC_MAX_SEQ_LENGTH}"
OPTS+=" --max_dec_length ${MAX_DEC_LENGTH}"
OPTS+=" --total_steps ${TOTAL_STEPS}"
OPTS+=" --outer_batch_size ${OUTER_BATCH_SIZE}"
OPTS+=" --save_step ${SAVE_STEP}"
OPTS+=" --test_step ${TEST_STEP}"
OPTS+=" --save_interval ${SAVE_INTERVAL}"
OPTS+=" --cluster_dir ${CLUSTER_DIR_1}  ${CLUSTER_DIR_2} ${CLUSTER_DIR_3}"
OPTS+=" --classify_num ${CLASSIFY_NUM}"
OPTS+=" --neg_sent ${NEG_SENT}"
printf "%-s" ${OPTS}
ulimit -n 4092
python ./pretrain.py ${OPTS}